### ISSUE TITLE
Give Option to not show author information

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/reconasia_wp#94]
Maesea requested the ability to not have to select an author for a post. Unfortunately that's not possible, but what we _can_ do is provide an option that allows us to not display the author information.

Let's add an ACF to posts that hides the author information if checked (make it a boolean field). Then we can modify [this function](https://github.com/CSIS-iLab/reconasia_wp/blob/main/wp-content/themes/reconasia/inc/template-tags.php#L190) so if the ACF is checked, it returns nothing instead of the coauthors list.

**Comment by jdromero88** [comment]
Hi @jnschrag
I added the ACF to dev.
[Here ](https://reconasiadev.wpengine.com/post-with-no-image-template/) is a post that is hiding the author so you can test it.
